version: '3'

services:
  node:
    image: node:12-alpine
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
    working_dir: /app
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    env_file:
      - .env
volumes:
  mongodata: